---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午12:04
---
local response = require('libs.response')
local google_search = require("libs.google_search")
local cjson = require("cjson")

local args = ngx.req.get_uri_args()
local keyword = args.keyword
ngx.log(ngx.DEBUG, '------args:--------' .. keyword)
if keyword then
    local page_index = 1
    local gsearch = google_search:new(keyword)
    local google_results = gsearch:search_youtube(page_index)
    if google_results then
        response.json_response(google_results)
        ngx.eof()

        --TODO
        -- cache the results?
        -- do some logging?
    else
        response.json_response({ msg = "no search results" })
    end
else
    response.json_response({ msg = "please input a keyword" }, 400)
end

