---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午12:04
---
local response = require('response')
local google_search = require("google_search")
local cjson = require("cjson")

local args = ngx.req.get_uri_args()
local keyword = args.keyword
if keyword then
    local google_results = google_search(keyword).search_youtube()
    if google_results then
        ngx.say(cjson.encode(google_results))
        ngx.eof()

        --TODO
        -- cache the results?
        -- do some logging?
    else
        response.json_response({msg="no search results"})
    end
else
    response.json_response({msg="please input a keyword"}, 400)
end

