---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午4:18
---
local args = ngx.req.get_uri_args()

local movie_hash = args.hash
if not movie_has then
    ngx.redirect("/")
end

html = string.format([[
<video id="player" width="100%" height="auto" autoplay="autoplay"  controls>';
        v_html+='<source src="/videos/%s'.mp4" type="video/mp4" codecs="avc1.42E01E, mp4a.40.2"> </video>';
]], movie_hash)
ngx.say(html)
