---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/18 下午12:18
---
local file_name = "/tmp/disk"
os.execute("df -h > " .. file_name)
local file_obj = io.open(file_name)
for line in file_obj:lines() do
    ngx.say(line)
end
