---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/18 上午9:49
---
local video_utils = require("libs.video_utils")
local response = require("libs.response")

local list = video_utils:get_downloaded_list()
local ret  = {}
for _, line in ipairs(list) do
    ret[#ret+1] = line
end
response.json_response(ret)
