---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午4:18
---
local args = ngx.req.get_uri_args()
local movie_hash = args.hash
ngx.log(ngx.DEBUG, "movie_hash is " .. movie_hash)
ngx.header['content-type']='text/html; charset=utf-8'
if not movie_hash then
    ngx.redirect("/")
end

html = string.format([[
<html>
<head>
<title>sights</title>
</head><body>
<video id="player" width="%s" height="auto" autoplay="autoplay"  controls>
<source src="/videos/%s.mp4" type="video/mp4" codecs="avc1.42E01E, mp4a.40.2"> </video>
</body>
</html>
]],'100%', movie_hash)
ngx.say(html)
