---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午4:25
---
local _T = {
    -- video status
    VIDEO_NOT_INITED = 0,
    VIDEO_DOWNLOADING = 1,
    VIDEO_DOWNLOADED = 2
}

function _T:get_video_hash(video_url)
    local resty_sha256 = require "resty.sha256"
    local str = require "resty.string"
    local sha256 = resty_sha256:new()
    sha256:update(video_url)
    local digest = sha256:final()
    return str.to_hex(digest)
end

return _T