---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午4:25
---
local _T = {
    -- video status
    VIDEO_NOT_INITED = 0,
    VIDEO_DOWNLOADING = 1,
    VIDEO_DOWNLOADED = 2
}

return _T