---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tommy.
--- DateTime: 2018/6/16 下午12:10
---

local _M = {}
local cjson = require("cjson")

function _M.json_response(table_obj, status, continue)
    ngx.header.content_type = "application/json;charset=utf-8"

    if not status then
        status = 200
    end
    ngx.status = status
    ngx.say(cjson.encode(table_obj))
    if continue then
        ngx.eof()
    else
        ngx.exit(ngx.HTTP_OK)
    end
end

return _M
